version: '3.8'

services:
  cinema-keeper:
    image: ghcr.io/nijeti/cinema-keeper:${APP_VERSION}
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT}
    networks:
      cinema-keeper_network:
    volumes:
      - ${CONFIG_FILE}:/app/appsettings.Production.json
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    networks:
      cinema-keeper_network:
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  cinema-keeper_network:

volumes:
  postgres:
