version: '3.8'

services:
  cinema-keeper:
    image: ghcr.io/nijeti/cinema-keeper:${APP_VERSION}
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT}
      Discord__BotToken: ${BOT_TOKEN}
      ConnectionStrings__Postgres: ${CS_POSTGRES}
    networks:
      cinema-keeper_network: null
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    networks:
      cinema-keeper_network: null
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  cinema-keeper_network: null

volumes:
  postgres: null
