name: Validate

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
  workflow_dispatch:

env:
  PROJECT_DIR: ./src/CinemaKeeper.Service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 5.0.x

      - name: Build
        run: dotnet build ${{ env.PROJECT_DIR }}
